version: "3"
    
services:
    db:
      image: postgres
      container_name: postgresdb
      env_file:
        - ./django/project.env
      ports:
        - 5432:5432
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

    web:
      build: ./django
      container_name: django
      volumes:
        - ./django/:/code
      env_file:
        - ./django/project.env
      depends_on:
        - db
#volumes:
#  postgres-data:
