version: "3"
    
services:
    company_db:
      image: postgres
      container_name: postgresdb
      env_file:
        - ./django/project.env
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

    company_web:
      build: ./django
      container_name: django
      volumes:
        - ./django/:/code
      env_file:
        - ./django/project.env
      ports:
        - 8000:8000
      depends_on:
        - company_db
#volumes:
#  postgres-data:
