# Generated by Django 3.1.1 on 2021-05-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.IntegerField()),
                ('name', models.CharField(max_length=26)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('N', 'new'), ('A', 'active'), ('O', 'old')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('inventarNr', models.CharField(max_length=14)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
            ],
        ),
    ]
