# Generated by Django 3.1.1 on 2021-05-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('A', 'active'), ('O', 'old')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='hardwareClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.hardwareclass'),
        ),
    ]
