# Generated by Django 3.1.1 on 2021-05-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='thing_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thing_content', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='handover',
            name='thing_object_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='handover',
            name='user_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_content', to='contenttypes.contenttype'),
        ),
    ]
