# Generated by Django 3.1.1 on 2021-06-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bulkarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='movementType',
            field=models.IntegerField(choices=[(21, 'Lay'), (22, 'Layback')], default=21),
        ),
    ]
