# Generated by Django 3.1.1 on 2021-06-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_handover_movementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='oppositeHandover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.handover'),
        ),
    ]
