# Generated by Django 3.2.8 on 2021-10-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210829_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
