# Generated by Django 3.2.8 on 2022-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_equipment_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
