# Generated by Django 3.0.4 on 2020-08-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networkmap', '0003_auto_20200724_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerName', models.CharField(max_length=26)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='networkmap.Device')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oSName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwareName', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=30)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Computer')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Software')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.OS'),
        ),
    ]
