# Generated by Django 3.1.1 on 2020-09-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=26)),
                ('inventNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwareName', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=30)),
                ('softwareType', models.CharField(choices=[('O', 'OS'), ('N', 'normal')], max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.device')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.software')),
            ],
        ),
    ]
