# Generated by Django 3.1.1 on 2020-09-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networkmap', '0001_initial'),
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='networkDevice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='networkmap.device'),
        ),
    ]
