# Generated by Django 3.1.1 on 2020-09-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkmap', '0001_initial'),
        ('computer', '0002_device_networkdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='inventNumber',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='device',
            name='networkDevice',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='networkmap.device'),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='computer.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='computer.devicemodel'),
        ),
    ]
