# Generated by Django 3.1.1 on 2021-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20200929_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventNumber',
            field=models.CharField(default='0000', max_length=16),
        ),
    ]
