# Generated by Django 3.0.4 on 2020-03-29 15:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('siteAPosition', models.IntegerField()),
                ('siteBPosition', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('siteA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteA', to='networkmap.Panel')),
                ('siteB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteB', to='networkmap.Panel')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(choices=[('NET', 'Network'), ('PWR', 'Power'), ('MNG', 'Management')], default='NET', max_length=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networkmap.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('partA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partA', to='networkmap.Port')),
                ('partB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partB', to='networkmap.Port')),
            ],
        ),
    ]
