# Generated by Django 3.0.4 on 2020-04-08 15:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('networkmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('classType', models.CharField(choices=[('D', 'Device'), ('T', 'Tunnel')], max_length=1)),
                ('type', models.CharField(choices=[('NET', 'Network'), ('PWR', 'Power'), ('MNG', 'Management')], default='NET', max_length=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networkmap.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PatchFieldPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('classType', models.CharField(choices=[('D', 'Device'), ('T', 'Tunnel')], max_length=1)),
                ('patchFieldPosition', models.IntegerField()),
                ('patchField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkmap.PatchField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='port',
            name='device',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='partA',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='partB',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='siteA',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='siteAPosition',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='siteB',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='siteBPosition',
        ),
        migrations.AddField(
            model_name='connection',
            name='portA_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='portA_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='networkmap_connection_relatedA', related_query_name='networkmap_connections', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='portB_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='portB_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='networkmap_connection_relatedB', related_query_name='networkmap_connections', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.AddField(
            model_name='tunnel',
            name='partA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partA', to='networkmap.PatchFieldPort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnel',
            name='partB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partB', to='networkmap.PatchFieldPort'),
            preserve_default=False,
        ),
    ]
